version: '3'

services:
  db-postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: db-server-manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: ["postgres", "-c", "listen_addresses=*"]

  init-db:
    image: postgres:latest
    depends_on:
      - db-postgres
    environment:
      POSTGRES_DB: db_server_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    command: ["createdb", "db-server-manager"]

volumes:
  postgres-data:
